Todo.create(task: "scaffold todos", complete: true)
Todo.create(task: "gemfile", complete: false)
Todo.create(task: "rails generate devise:install (follow the instructions in terminal)", complete: false)
Todo.create(task: "rails generate devise user", complete: false)
Todo.create(task: "rails generate devise:views (to customize the views)", complete: false)
Todo.create(task: "use helpers to add logout buttun when appropriate", complete: false)
Todo.create(task: "config/intializers/devise.rb", complete: false)
Todo.create(task: "routes.rb", complete: false)
Todo.create(task: "omniauth_callbacks_controller.rb", complete: false)
Todo.create(task: "rails generate AddProviderAndUidToUsers", complete: false)
